### ISSUE TITLE
Transpile and minify the code

### ISSUE THREAD

**Issue by jaaberg** [derhuerst/svg-partial-circle#1]
I suggest that you transpile (and uglify/minify) the code. You are now exporting the function as an arrow function, which breaks things since node_modules usually isn't transpiled. 

Ex: I have a project created by create-react-app. I use this package as a dependency. Building my app crashes since node_modules are not transpiled and thus is not supporting arrow functions. 

At least I suggest that you export a normal function and not an arrow function. 

Another good point is that functions are hoisted (meaning they can be accessed before they are declared), which is a useful attribute in a static utility function.

**Comment by derhuerst** [comment]
@jaaberg My opinion on this is very similar to the one of a well-known JS dev i won't bother by mentioning here. See facebookincubator/create-react-app#1125 and https://github.com/sindresorhus/ama/issues/446#issuecomment-281014491 for more details.

Specifically, I tend to stay on the more lightweight side in terms of how much tooling to add to projects. I usually don't add transpiling, code coverage or linting tools.

I mostly see the whole issue of preparing JS for the browser as a consumer's problem. Also, I don't know about the context consumers are going to use my libraries:

- Node.js or Browser
- which feature level & ES version? ES3? ES5? ES6?
- build setup, how to provide polyfills, etc.

I try to keep *their code* (edit: the libraries' code) as isomorphic as possible, but have their *build setup* as simple as possible.

That being said, **I don't ignore the Browser side.** I intend to have my libs being usable in general, e.g. by using `isomorphic-fetch`. If you come across anything that outright breaks in the browser and can't be fixed by tooling, let me know!

> At least I suggest that you export a normal function and not an arrow function.

I'm happy to add a `module`/`es2015`/whatever field to `package.json` to make it easier for bundlers to transpile my lib.

---

> I have a project created by create-react-app. I use this package as a dependency.

I'd be interested which!

**Comment by jaaberg** [comment]
Thanks for a well formulated answer. As a browser side consumer, I didn't see the whole picture. I definitely understand you, but may not yet be totally convinced which side I am on in that discussion (ref. your link).

> I'd be interested which!

Actually, I simplified it a little bit. I was using [react-minimal-pie-chart](https://github.com/toomuchdesign/react-minimal-pie-chart) in which again used this package. 

I solved it the fastest way for my self by just forking that project and fix the problem so that it worked for my use case. I am only using it in a prototype anyways, so maintainability was not a priority, so no need fixing anything for me. I was just trying to be helpful in case you hadn't thought about it :)
